swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /products:
      # our controller name
      x-swagger-router-controller: hello_world
      get:
        description: get the products list
        # define the type of response for Success "200" and Error
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/GetProductsListResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"

      post:
        description: add a new product to the list
        # product info to be stored
        parameters:
          - name: name
            description: Product properties
            in: body
            required: true
            schema:
              $ref: "#/definitions/Product"
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/GeneralResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
              
  /products/{id}:
    # our controller name
    x-swagger-router-controller: hello_world
    get:
      description: get a product
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetProductResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
    delete:
      description: delete a product
      # define the parameters
      parameters:
        - name: id
          description: Product id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /users:
      # our controller name
      x-swagger-router-controller: hello_world
      get:
        description: get the users list
        # define the type of response for Success "200" and Error
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/GetUsersListResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"


  /users/{id}:
    # our controller name
    x-swagger-router-controller: hello_world   
    delete:
      description: delete a user
      # define the parameters
      parameters:
        - name: id
          description: User id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"  

  /cities:
      # our controller name
      x-swagger-router-controller: hello_world
      get:
        description: get the cities list
        # define the type of response for Success "200" and Error
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/GetCitiesListResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse" 
              
      post:
        description: add a new city to the list
        # product info to be stored
        parameters:
          - name: name
            description: City properties
            in: body
            required: true
            schema:
              $ref: "#/definitions/City"
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/GeneralResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
              
  /cities/{id}:
    # our controller name
    x-swagger-router-controller: hello_world   
    put:
      description: update a city
      # define the parameters
      parameters:
        - name: id
          description: City id
          type: string
          in: path
          required: true
        - name: title
          description: City properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/City"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
    delete:
      description: delete a city
      # define the parameters
      parameters:
        - name: id
          description: User id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"           

# complex objects have schema definitions
definitions:

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        
  GetProductsListResponse:
    required:
      - products
    properties:
      products:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            price:
              type: number
              
  GetProductResponse:
    required:
      - id
      - name
      - price
    properties:
      id:
        type: string
      name: 
        type: string
      price:
        type: number
        
  Product:
    type: object
    properties:
      name:
        type: string
        description: task object name
      price:
        type: number
        description: task description
    required:
      - name
      - price

  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description


  GetUsersListResponse:
    required:
        - users
    properties:
      users:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            username:
              type: string
            password:
              type: string

  GetCitiesListResponse:
    required:
        - cities
    properties:
      cities:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            country:
              type: string
            capital:
              type: boolean
            location:
              type: object
              properties:
                lat:
                  type: string
                long:
                  type: string
                  
  City:
    type: object
    properties:
      name:
        type: string
        description: task object name
      country:
        type: number
        description: task description
      capital:
        type: boolean
        description: is the city capital or not
      location:
        type: object
        properties:
          lat: 
            type: string
          long: 
            type: string
    required:
      - name
      - country           
      - capital
      - location